<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataIDProviders = array(
    'urn:mace:cru.fr:federation:sac' =>
        array(
            'SSO' => 'https://cru.renater.fr/idp/profile/Shibboleth/SSO',
            'Name' => 'Comptes CRU',
            'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:mace:shibboleth:1.0 urn:oasis:names:tc:SAML:2.0:protocol',
        )
);
?>
