<?php

// This file was automatically generated by readMetadata.php
// Don't edit!

$metadataSProviders = array ();
if ($developmentMode) {
    $metadataSProviders = array (
      'https://aaa.sygefor.reseau-urfist.fr' =>
          array (
            'Name' => 'Sygefor3 Recette',
            'ACURL' =>
                array (
                  0 => 'https://sygefor.com/Shibboleth.sso/SAML/POST',
                  1 => 'https://sygefor.com/Shibboleth.sso/SAML2/POST',
                ),
            'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol urn:oasis:names:tc:SAML:2.0:protocol',
          ),
    );
}
else {
    $metadataSProviders = array (
        'https://sygefor-shibboleth-isp.fr' =>
            array (
                'Name' => 'Sygefor',
                'ACURL' =>
                    array (
                        1 => 'https://sygefor.com/Shibboleth.sso/SAML/POST',
                        2 => 'https://sygefor.com/Shibboleth.sso/SAML2/POST',
                    ),
                'Protocols' => 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:1.0:protocol urn:oasis:names:tc:SAML:2.0:protocol',
            ),
    );
}

?>